<?php

namespace App\Presenters;

use Nette;
use App\Model;


/**
 * Base presenter for all application presenters.
 */
abstract class BasePresenter extends Nette\Application\UI\Presenter
{
    public function formatLayoutTemplateFiles()
    {
        $templates = parent::formatLayoutTemplateFiles();
        echo "CALLED";
        return parent::formatLayoutTemplateFiles(); // TODO: Change the autogenerated stub
    }
}
